<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="33" passed="28" failed="5" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-06-21T17:34:36Z" name="Suite" finished-at="2019-06-21T17:35:24Z" duration-ms="47940">
    <groups>
    </groups>
    <test started-at="2019-06-21T17:34:36Z" name="Test" finished-at="2019-06-21T17:35:24Z" duration-ms="47940">
      <class name="com.employeeapitestcases.TC003_POST_Employee_Record">
        <test-method is-config="true" signature="createEmployee()[pri:0, instance:com.employeeapitestcases.TC003_POST_Employee_Record@5aebe890]" started-at="2019-06-21T17:35:07Z" name="createEmployee" finished-at="2019-06-21T17:35:13Z" duration-ms="5263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createEmployee -->
        <test-method signature="checkContentEncoding()[pri:0, instance:com.employeeapitestcases.TC003_POST_Employee_Record@5aebe890]" started-at="2019-06-21T17:35:13Z" name="checkContentEncoding" finished-at="2019-06-21T17:35:13Z" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentEncoding -->
        <test-method signature="checkContentType()[pri:0, instance:com.employeeapitestcases.TC003_POST_Employee_Record@5aebe890]" started-at="2019-06-21T17:35:13Z" name="checkContentType" finished-at="2019-06-21T17:35:13Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentType -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.employeeapitestcases.TC003_POST_Employee_Record@5aebe890]" started-at="2019-06-21T17:35:13Z" name="checkResponseBody" finished-at="2019-06-21T17:35:13Z" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.employeeapitestcases.TC003_POST_Employee_Record.checkResponseBody(TC003_POST_Employee_Record.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkResponseTime()[pri:0, instance:com.employeeapitestcases.TC003_POST_Employee_Record@5aebe890]" started-at="2019-06-21T17:35:13Z" name="checkResponseTime" finished-at="2019-06-21T17:35:13Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method signature="checkserverType()[pri:0, instance:com.employeeapitestcases.TC003_POST_Employee_Record@5aebe890]" started-at="2019-06-21T17:35:13Z" name="checkserverType" finished-at="2019-06-21T17:35:13Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkserverType -->
        <test-method signature="checkstatusLine()[pri:0, instance:com.employeeapitestcases.TC003_POST_Employee_Record@5aebe890]" started-at="2019-06-21T17:35:13Z" name="checkstatusLine" finished-at="2019-06-21T17:35:13Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatusLine -->
        <test-method signature="checkstatuscode()[pri:0, instance:com.employeeapitestcases.TC003_POST_Employee_Record@5aebe890]" started-at="2019-06-21T17:35:13Z" name="checkstatuscode" finished-at="2019-06-21T17:35:13Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatuscode -->
      </class> <!-- com.employeeapitestcases.TC003_POST_Employee_Record -->
      <class name="com.employeeapitestcases.TC001_GET_All_Employees">
        <test-method is-config="true" signature="getAllemployees()[pri:0, instance:com.employeeapitestcases.TC001_GET_All_Employees@394df057]" started-at="2019-06-21T17:34:36Z" name="getAllemployees" finished-at="2019-06-21T17:34:43Z" duration-ms="6583" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllemployees -->
        <test-method signature="checkContentType()[pri:0, instance:com.employeeapitestcases.TC001_GET_All_Employees@394df057]" started-at="2019-06-21T17:34:43Z" name="checkContentType" finished-at="2019-06-21T17:34:43Z" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentType -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.employeeapitestcases.TC001_GET_All_Employees@394df057]" started-at="2019-06-21T17:34:43Z" name="checkResponseBody" finished-at="2019-06-21T17:34:43Z" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkResponseTime()[pri:0, instance:com.employeeapitestcases.TC001_GET_All_Employees@394df057]" started-at="2019-06-21T17:34:43Z" name="checkResponseTime" finished-at="2019-06-21T17:34:43Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method signature="checkstatusLine()[pri:0, instance:com.employeeapitestcases.TC001_GET_All_Employees@394df057]" started-at="2019-06-21T17:34:43Z" name="checkstatusLine" finished-at="2019-06-21T17:34:43Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatusLine -->
        <test-method signature="checkstatuscode()[pri:0, instance:com.employeeapitestcases.TC001_GET_All_Employees@394df057]" started-at="2019-06-21T17:34:43Z" name="checkstatuscode" finished-at="2019-06-21T17:34:43Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatuscode -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.employeeapitestcases.TC001_GET_All_Employees@394df057]" started-at="2019-06-21T17:34:43Z" name="tearDown" finished-at="2019-06-21T17:34:43Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.employeeapitestcases.TC001_GET_All_Employees -->
      <class name="com.employeeapitestcases.TC002_GET_single_Employee_Record">
        <test-method is-config="true" signature="getEmployeeData()[pri:0, instance:com.employeeapitestcases.TC002_GET_single_Employee_Record@4961f6af]" started-at="2019-06-21T17:34:43Z" name="getEmployeeData" finished-at="2019-06-21T17:35:07Z" duration-ms="24571" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getEmployeeData -->
        <test-method signature="checkContentLength()[pri:0, instance:com.employeeapitestcases.TC002_GET_single_Employee_Record@4961f6af]" started-at="2019-06-21T17:35:07Z" name="checkContentLength" finished-at="2019-06-21T17:35:07Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentLength -->
        <test-method signature="checkContentType()[pri:0, instance:com.employeeapitestcases.TC002_GET_single_Employee_Record@4961f6af]" started-at="2019-06-21T17:35:07Z" name="checkContentType" finished-at="2019-06-21T17:35:07Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentType -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.employeeapitestcases.TC002_GET_single_Employee_Record@4961f6af]" started-at="2019-06-21T17:35:07Z" name="checkResponseBody" finished-at="2019-06-21T17:35:07Z" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<false> but was:<true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:147)
at com.employeeapitestcases.TC002_GET_single_Employee_Record.checkResponseBody(TC002_GET_single_Employee_Record.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkResponseTime()[pri:0, instance:com.employeeapitestcases.TC002_GET_single_Employee_Record@4961f6af]" started-at="2019-06-21T17:35:07Z" name="checkResponseTime" finished-at="2019-06-21T17:35:07Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at com.employeeapitestcases.TC002_GET_single_Employee_Record.checkResponseTime(TC002_GET_single_Employee_Record.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method signature="checkserverType()[pri:0, instance:com.employeeapitestcases.TC002_GET_single_Employee_Record@4961f6af]" started-at="2019-06-21T17:35:07Z" name="checkserverType" finished-at="2019-06-21T17:35:07Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkserverType -->
        <test-method signature="checkstatusLine()[pri:0, instance:com.employeeapitestcases.TC002_GET_single_Employee_Record@4961f6af]" started-at="2019-06-21T17:35:07Z" name="checkstatusLine" finished-at="2019-06-21T17:35:07Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatusLine -->
        <test-method signature="checkstatuscode()[pri:0, instance:com.employeeapitestcases.TC002_GET_single_Employee_Record@4961f6af]" started-at="2019-06-21T17:35:07Z" name="checkstatuscode" finished-at="2019-06-21T17:35:07Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatuscode -->
      </class> <!-- com.employeeapitestcases.TC002_GET_single_Employee_Record -->
      <class name="com.employeeapitestcases.TC004_PUT_Employee_Record">
        <test-method is-config="true" signature="updateEmployee()[pri:0, instance:com.employeeapitestcases.TC004_PUT_Employee_Record@65d09a04]" started-at="2019-06-21T17:35:13Z" name="updateEmployee" finished-at="2019-06-21T17:35:18Z" duration-ms="5468" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateEmployee -->
        <test-method signature="checkContentEncoding()[pri:0, instance:com.employeeapitestcases.TC004_PUT_Employee_Record@65d09a04]" started-at="2019-06-21T17:35:18Z" name="checkContentEncoding" finished-at="2019-06-21T17:35:18Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentEncoding -->
        <test-method signature="checkContentType()[pri:0, instance:com.employeeapitestcases.TC004_PUT_Employee_Record@65d09a04]" started-at="2019-06-21T17:35:18Z" name="checkContentType" finished-at="2019-06-21T17:35:18Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentType -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.employeeapitestcases.TC004_PUT_Employee_Record@65d09a04]" started-at="2019-06-21T17:35:18Z" name="checkResponseBody" finished-at="2019-06-21T17:35:18Z" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.employeeapitestcases.TC004_PUT_Employee_Record.checkResponseBody(TC004_PUT_Employee_Record.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkResponseTime()[pri:0, instance:com.employeeapitestcases.TC004_PUT_Employee_Record@65d09a04]" started-at="2019-06-21T17:35:18Z" name="checkResponseTime" finished-at="2019-06-21T17:35:18Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method signature="checkserverType()[pri:0, instance:com.employeeapitestcases.TC004_PUT_Employee_Record@65d09a04]" started-at="2019-06-21T17:35:18Z" name="checkserverType" finished-at="2019-06-21T17:35:18Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkserverType -->
        <test-method signature="checkstatusLine()[pri:0, instance:com.employeeapitestcases.TC004_PUT_Employee_Record@65d09a04]" started-at="2019-06-21T17:35:18Z" name="checkstatusLine" finished-at="2019-06-21T17:35:18Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatusLine -->
        <test-method signature="checkstatuscode()[pri:0, instance:com.employeeapitestcases.TC004_PUT_Employee_Record@65d09a04]" started-at="2019-06-21T17:35:18Z" name="checkstatuscode" finished-at="2019-06-21T17:35:18Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatuscode -->
      </class> <!-- com.employeeapitestcases.TC004_PUT_Employee_Record -->
      <class name="com.employeeapitestcases.TC005_DELETE_Employee_Record">
        <test-method is-config="true" signature="deleteEmployee()[pri:0, instance:com.employeeapitestcases.TC005_DELETE_Employee_Record@33c911a1]" started-at="2019-06-21T17:35:18Z" name="deleteEmployee" finished-at="2019-06-21T17:35:24Z" duration-ms="5912" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteEmployee -->
        <test-method signature="checkContentEncoding()[pri:0, instance:com.employeeapitestcases.TC005_DELETE_Employee_Record@33c911a1]" started-at="2019-06-21T17:35:24Z" name="checkContentEncoding" finished-at="2019-06-21T17:35:24Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentEncoding -->
        <test-method signature="checkContentType()[pri:0, instance:com.employeeapitestcases.TC005_DELETE_Employee_Record@33c911a1]" started-at="2019-06-21T17:35:24Z" name="checkContentType" finished-at="2019-06-21T17:35:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContentType -->
        <test-method signature="checkResponseBody()[pri:0, instance:com.employeeapitestcases.TC005_DELETE_Employee_Record@33c911a1]" started-at="2019-06-21T17:35:24Z" name="checkResponseBody" finished-at="2019-06-21T17:35:24Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.employeeapitestcases.TC005_DELETE_Employee_Record.checkResponseBody(TC005_DELETE_Employee_Record.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseBody -->
        <test-method signature="checkResponseTime()[pri:0, instance:com.employeeapitestcases.TC005_DELETE_Employee_Record@33c911a1]" started-at="2019-06-21T17:35:24Z" name="checkResponseTime" finished-at="2019-06-21T17:35:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkResponseTime -->
        <test-method signature="checkserverType()[pri:0, instance:com.employeeapitestcases.TC005_DELETE_Employee_Record@33c911a1]" started-at="2019-06-21T17:35:24Z" name="checkserverType" finished-at="2019-06-21T17:35:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkserverType -->
        <test-method signature="checkstatuscode()[pri:0, instance:com.employeeapitestcases.TC005_DELETE_Employee_Record@33c911a1]" started-at="2019-06-21T17:35:24Z" name="checkstatuscode" finished-at="2019-06-21T17:35:24Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatuscode -->
        <test-method signature="checkstatusLine()[pri:0, instance:com.employeeapitestcases.TC005_DELETE_Employee_Record@33c911a1]" started-at="2019-06-21T17:35:24Z" name="checkstatusLine" finished-at="2019-06-21T17:35:24Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkstatusLine -->
      </class> <!-- com.employeeapitestcases.TC005_DELETE_Employee_Record -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
